name: ourESchool
description: A School Management Project
publish_to: "none"
version: 1.0.0-dev.1.0.1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  camera: ^0.8.1
  # cloud_firestore: 0.16.0
  cloud_firestore: ^2.1.0
  cupertino_icons: ^1.0.3
  custom_radio_grouped_button: ^1.0.6+1
  dio: ^4.0.0
  division: ^0.8.8
  file_picker: ^3.0.1
  # firebase_auth: 0.20.0+1
  # firebase_core: 0.7.0
  # firebase_storage: 7.0.0
  firebase_auth: ^1.1.4
  firebase_core: ^1.1.1
  firebase_storage: ^8.0.6
  syncfusion_flutter_pdfviewer: ^19.1.63-beta
  # flutter_plugin_pdf_viewer: ^1.0.7
  flutter_spinkit: ^5.0.0
  font_awesome_flutter: ^9.0.0
  get_it: ^7.1.3
  http: ^0.13.3
  image: ^3.0.2
  image_picker: ^0.7.5
  image_picker_for_web: ^2.0.0
  intl: ^0.17.0
  intro_views_flutter: ^3.1.0
  path_provider: ^2.0.1
  permission_handler: ^7.1.0
  photo_view: ^0.11.1
  provider: ^5.0.0
  random_color: ^1.0.5
  shared_preferences: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

# dependency_overrides:
#   rxdart: ^0.22.0
flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Customicons
      fonts:
        - asset: assets/fonts/Customicons.ttf

    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf

    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-Black.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-ExtraBold.ttf
          weight: 900
        - asset: assets/fonts/Nunito-Italic.ttf
